const User = require('../models/User');
const Crop = require('../models/Crop');
const MarketPrice = require('../models/MarketPrice');
const Offer = require('../models/Offer');
const Order = require('../models/Order');
const PriceAlert = require('../models/PriceAlert');
const GovernmentScheme = require('../models/GovernmentScheme');
const CropAdvisory = require('../models/CropAdvisory');

const seedData = async () => {
  try {
    const userCount = await User.countDocuments();
    if (userCount > 0) {
      console.log('Database already contains records. Skipping full seeding.');
      return;
    }

    console.log('🌱 Empty database detected. Seeding comprehensive KisanSetu dataset...');

    // 1. Seed Users
    const farmerRamesh = await User.create({
      name: 'Ramesh Patel',
      email: 'farmer@kisansetu.com',
      password: 'farmer123',
      role: 'farmer',
      phone: '+91 98765 43210',
      businessName: 'Patel Organic Farms',
      avatar: 'https://images.unsplash.com/photo-1544717305-2782549b5136?w=200&auto=format&fit=crop&q=80',
      isVerified: true,
      rating: 4.9,
      reviewsCount: 38,
      totalDeals: 24,
      location: {
        village: 'Kotda Sangani',
        district: 'Rajkot',
        state: 'Gujarat',
        pincode: '360030',
      },
    });

    const buyerPriya = await User.create({
      name: 'Priya Sharma',
      email: 'buyer@kisansetu.com',
      password: 'buyer123',
      role: 'buyer',
      phone: '+91 98234 56789',
      businessName: 'Reliance Fresh Agri Procurement',
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=200&auto=format&fit=crop&q=80',
      isVerified: true,
      rating: 4.8,
      reviewsCount: 52,
      totalDeals: 110,
      location: {
        village: 'Udhna Hub',
        district: 'Surat',
        state: 'Gujarat',
        pincode: '394210',
      },
    });

    const adminUser = await User.create({
      name: 'KisanSetu Admin',
      email: 'admin@kisansetu.com',
      password: 'admin123',
      role: 'admin',
      phone: '+91 99999 00000',
      businessName: 'KisanSetu Agricultural Exchange',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=200&auto=format&fit=crop&q=80',
      isVerified: true,
      location: {
        village: 'Gandhinagar Tech Zone',
        district: 'Gandhinagar',
        state: 'Gujarat',
        pincode: '382010',
      },
    });

    const buyerAgroCorp = await User.create({
      name: 'Vikram Mehta',
      email: 'agrocorp@gmail.com',
      password: 'buyer123',
      role: 'buyer',
      phone: '+91 91234 56780',
      businessName: 'AgroCorp Global Exports',
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&auto=format&fit=crop&q=80',
      isVerified: true,
      rating: 4.7,
      reviewsCount: 29,
      totalDeals: 76,
      location: {
        village: 'Sanand Industrial Estate',
        district: 'Ahmedabad',
        state: 'Gujarat',
        pincode: '382110',
      },
    });

    // 2. Seed Mandi Prices
    const mandiPricesData = [
      // Wheat
      {
        cropName: 'Wheat',
        variety: 'Sharbati / Lokwan',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Gondal Mandi',
        minPrice: 2340,
        maxPrice: 2520,
        modalPrice: 2450,
        priceChange: 45,
        priceChangePercent: 1.87,
        trend: 'rising',
        arrivalQuantity: 320,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      {
        cropName: 'Wheat',
        variety: 'Sharbati',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Rajkot APMC',
        minPrice: 2310,
        maxPrice: 2480,
        modalPrice: 2420,
        priceChange: 30,
        priceChangePercent: 1.25,
        trend: 'rising',
        arrivalQuantity: 460,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 22.3039, lng: 70.8022 },
      },
      {
        cropName: 'Wheat',
        variety: 'Lokwan',
        state: 'Gujarat',
        district: 'Mehsana',
        market: 'Unjha Mandi',
        minPrice: 2360,
        maxPrice: 2540,
        modalPrice: 2475,
        priceChange: 55,
        priceChangePercent: 2.27,
        trend: 'rising',
        arrivalQuantity: 180,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 23.8016, lng: 72.3917 },
      },
      {
        cropName: 'Wheat',
        variety: 'Mill Quality',
        state: 'Gujarat',
        district: 'Ahmedabad',
        market: 'Ahmedabad (APMC Jamalpur)',
        minPrice: 2280,
        maxPrice: 2440,
        modalPrice: 2390,
        priceChange: -10,
        priceChangePercent: -0.42,
        trend: 'falling',
        arrivalQuantity: 380,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 23.0225, lng: 72.5714 },
      },
      {
        cropName: 'Wheat',
        variety: 'Lokwan',
        state: 'Gujarat',
        district: 'Surat',
        market: 'Surat APMC',
        minPrice: 2300,
        maxPrice: 2460,
        modalPrice: 2410,
        priceChange: 15,
        priceChangePercent: 0.63,
        trend: 'stable',
        arrivalQuantity: 210,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.1702, lng: 72.8311 },
      },
      {
        cropName: 'Wheat',
        variety: 'Kalyan Sona',
        state: 'Punjab',
        district: 'Ludhiana',
        market: 'Khanna Mandi',
        minPrice: 2350,
        maxPrice: 2490,
        modalPrice: 2435,
        priceChange: 25,
        priceChangePercent: 1.04,
        trend: 'rising',
        arrivalQuantity: 850,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 30.7022, lng: 76.2205 },
      },
      // Cotton
      {
        cropName: 'Cotton',
        variety: 'Shankar-6',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Rajkot APMC',
        minPrice: 7200,
        maxPrice: 7750,
        modalPrice: 7520,
        priceChange: 110,
        priceChangePercent: 1.48,
        trend: 'rising',
        arrivalQuantity: 410,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 22.3039, lng: 70.8022 },
      },
      {
        cropName: 'Cotton',
        variety: 'Shankar-6 Medium Staple',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Gondal Mandi',
        minPrice: 7250,
        maxPrice: 7820,
        modalPrice: 7580,
        priceChange: 130,
        priceChangePercent: 1.74,
        trend: 'rising',
        arrivalQuantity: 340,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      {
        cropName: 'Cotton',
        variety: 'Medium Staple',
        state: 'Gujarat',
        district: 'Surendranagar',
        market: 'Surendranagar APMC',
        minPrice: 7100,
        maxPrice: 7650,
        modalPrice: 7420,
        priceChange: 0,
        priceChangePercent: 0,
        trend: 'stable',
        arrivalQuantity: 280,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 22.7279, lng: 71.6375 },
      },
      // Tomato
      {
        cropName: 'Tomato',
        variety: 'Hybrid / Vaishali',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Rajkot APMC',
        minPrice: 1650,
        maxPrice: 2150,
        modalPrice: 1940,
        priceChange: 80,
        priceChangePercent: 4.3,
        trend: 'rising',
        arrivalQuantity: 115,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 22.3039, lng: 70.8022 },
      },
      {
        cropName: 'Tomato',
        variety: 'Local Ripe',
        state: 'Gujarat',
        district: 'Surat',
        market: 'Surat APMC',
        minPrice: 1850,
        maxPrice: 2350,
        modalPrice: 2180,
        priceChange: 120,
        priceChangePercent: 5.83,
        trend: 'rising',
        arrivalQuantity: 90,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.1702, lng: 72.8311 },
      },
      {
        cropName: 'Tomato',
        variety: 'Desi',
        state: 'Maharashtra',
        district: 'Nashik',
        market: 'Pimpalgaon Mandi',
        minPrice: 1500,
        maxPrice: 1950,
        modalPrice: 1780,
        priceChange: -60,
        priceChangePercent: -3.26,
        trend: 'falling',
        arrivalQuantity: 420,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 20.1683, lng: 73.9873 },
      },
      // Onion
      {
        cropName: 'Onion',
        variety: 'Red Garva',
        state: 'Maharashtra',
        district: 'Nashik',
        market: 'Lasalgaon APMC',
        minPrice: 2400,
        maxPrice: 2950,
        modalPrice: 2720,
        priceChange: 90,
        priceChangePercent: 3.42,
        trend: 'rising',
        arrivalQuantity: 740,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 20.1478, lng: 74.2267 },
      },
      {
        cropName: 'Onion',
        variety: 'White Onion',
        state: 'Gujarat',
        district: 'Bhavnagar',
        market: 'Mahuva Mandi',
        minPrice: 2250,
        maxPrice: 2750,
        modalPrice: 2540,
        priceChange: 50,
        priceChangePercent: 2.01,
        trend: 'rising',
        arrivalQuantity: 360,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.0914, lng: 71.7618 },
      },
      {
        cropName: 'Onion',
        variety: 'Red Onion',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Gondal Mandi',
        minPrice: 2320,
        maxPrice: 2820,
        modalPrice: 2610,
        priceChange: 40,
        priceChangePercent: 1.56,
        trend: 'rising',
        arrivalQuantity: 210,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      // Groundnut
      {
        cropName: 'Groundnut',
        variety: 'Bold G-20',
        state: 'Gujarat',
        district: 'Rajkot',
        market: 'Gondal Mandi',
        minPrice: 6050,
        maxPrice: 6850,
        modalPrice: 6490,
        priceChange: 75,
        priceChangePercent: 1.17,
        trend: 'rising',
        arrivalQuantity: 380,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      {
        cropName: 'Groundnut',
        variety: 'GG-2',
        state: 'Gujarat',
        district: 'Junagadh',
        market: 'Junagadh APMC',
        minPrice: 6100,
        maxPrice: 6900,
        modalPrice: 6540,
        priceChange: 90,
        priceChangePercent: 1.39,
        trend: 'rising',
        arrivalQuantity: 290,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 21.5222, lng: 70.4579 },
      },
      // Cumin (Jeera)
      {
        cropName: 'Cumin',
        variety: 'Machine Cleaned Export Quality',
        state: 'Gujarat',
        district: 'Mehsana',
        market: 'Unjha Mandi',
        minPrice: 25400,
        maxPrice: 29800,
        modalPrice: 27500,
        priceChange: 450,
        priceChangePercent: 1.66,
        trend: 'rising',
        arrivalQuantity: 140,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 23.8016, lng: 72.3917 },
      },
      // Potato
      {
        cropName: 'Potato',
        variety: 'Kufri Pukhraj / Badshah',
        state: 'Gujarat',
        district: 'Banaskantha',
        market: 'Deesa APMC',
        minPrice: 1280,
        maxPrice: 1620,
        modalPrice: 1460,
        priceChange: 20,
        priceChangePercent: 1.39,
        trend: 'rising',
        arrivalQuantity: 520,
        arrivalUnit: 'Tonnes',
        coordinates: { lat: 24.2586, lng: 72.1802 },
      },
    ];

    await MarketPrice.insertMany(mandiPricesData);

    // 3. Seed Crop Listings
    const cropWheat = await Crop.create({
      farmer: farmerRamesh._id,
      cropName: 'Sharbati Wheat',
      variety: 'Sharbati Premium Gold',
      category: 'Grains',
      quantity: 120,
      unit: 'quintal',
      minOrderQuantity: 10,
      pricePerUnit: 2420,
      qualityGrade: 'Grade A',
      moistureContent: 10.8,
      isOrganic: true,
      description: 'Sun-dried high protein Sharbati wheat grown using certified organic cow dung compost. Golden plump grains, 100% pest-free.',
      images: ['https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?w=600&auto=format&fit=crop&q=80'],
      location: {
        village: 'Kotda Sangani',
        district: 'Rajkot',
        state: 'Gujarat',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      status: 'available',
    });

    const cropCotton = await Crop.create({
      farmer: farmerRamesh._id,
      cropName: 'Raw Shankar-6 Cotton',
      variety: 'Shankar-6 Long Staple',
      category: 'Other',
      quantity: 85,
      unit: 'quintal',
      minOrderQuantity: 15,
      pricePerUnit: 7480,
      qualityGrade: 'Grade A',
      moistureContent: 8.2,
      isOrganic: false,
      description: 'First picking superior quality long-staple Shankar-6 white cotton. High ginning outturn and minimal trash content.',
      images: ['https://images.unsplash.com/photo-1606041008023-472dfb5e530f?w=600&auto=format&fit=crop&q=80'],
      location: {
        village: 'Kotda Sangani',
        district: 'Rajkot',
        state: 'Gujarat',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      status: 'available',
    });

    const cropGroundnut = await Crop.create({
      farmer: farmerRamesh._id,
      cropName: 'Bold Groundnut (Singdana)',
      variety: 'G-20 Bold',
      category: 'Oilseeds',
      quantity: 60,
      unit: 'quintal',
      minOrderQuantity: 10,
      pricePerUnit: 6450,
      qualityGrade: 'Grade A',
      moistureContent: 7.5,
      isOrganic: true,
      description: 'Rich oil content 49% bold Saurashtra groundnuts. Ready for oil crushing or edible kernel export.',
      images: ['https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=600&auto=format&fit=crop&q=80'],
      location: {
        village: 'Kotda Sangani',
        district: 'Rajkot',
        state: 'Gujarat',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      status: 'available',
    });

    const cropTomato = await Crop.create({
      farmer: farmerRamesh._id,
      cropName: 'Red Table Tomato',
      variety: 'Abhinav Hybrid',
      category: 'Vegetables',
      quantity: 45,
      unit: 'quintal',
      minOrderQuantity: 5,
      pricePerUnit: 1880,
      qualityGrade: 'Grade A',
      moistureContent: 91.0,
      isOrganic: false,
      description: 'Firm, uniform scarlet red tomatoes harvested fresh this morning. Thick skin suitable for long-haul transport without spoilage.',
      images: ['https://images.unsplash.com/photo-1592924357228-91a4daadcfea?w=600&auto=format&fit=crop&q=80'],
      location: {
        village: 'Kotda Sangani',
        district: 'Rajkot',
        state: 'Gujarat',
        coordinates: { lat: 21.9619, lng: 70.7937 },
      },
      status: 'available',
    });

    // 4. Seed Initial Offer & Order
    const sampleOffer = await Offer.create({
      crop: cropWheat._id,
      buyer: buyerPriya._id,
      farmer: farmerRamesh._id,
      offeredPrice: 2400,
      quantity: 40,
      totalAmount: 96000,
      status: 'accepted',
      deliveryTerms: 'Buyer Arranged Logistics',
      paymentTerms: 'Escrow Released On Inspection',
      message: 'Looking for 40 quintals of Sharbati Grade A for our Surat retail outlets. Can dispatch truck by Friday.',
    });

    const sampleOrder = await Order.create({
      crop: cropWheat._id,
      buyer: buyerPriya._id,
      farmer: farmerRamesh._id,
      offer: sampleOffer._id,
      quantity: 40,
      unit: 'quintal',
      pricePerUnit: 2400,
      totalAmount: 96000,
      orderStatus: 'in_transit',
      paymentStatus: 'in_escrow',
      paymentMethod: 'Escrow',
      trackingNumber: 'KS-849201',
      estimatedDeliveryDate: new Date(Date.now() + 2 * 24 * 60 * 60 * 1000),
      shippingAddress: {
        street: 'Reliance Fresh Regional Distribution Hub, Ring Road',
        district: 'Surat',
        state: 'Gujarat',
        pincode: '395002',
      },
      timeline: [
        { status: 'placed', note: 'Order placed from accepted offer', timestamp: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000) },
        { status: 'confirmed', note: 'Farmer Ramesh Patel confirmed harvest & packing', timestamp: new Date(Date.now() - 1 * 24 * 60 * 60 * 1000) },
        { status: 'in_transit', note: 'Loaded onto logistics truck MH-04-AB-1294', timestamp: new Date() },
      ],
    });

    // An active pending offer for the farmer to review and accept
    await Offer.create({
      crop: cropCotton._id,
      buyer: buyerAgroCorp._id,
      farmer: farmerRamesh._id,
      offeredPrice: 7420,
      quantity: 30,
      totalAmount: 222600,
      status: 'pending',
      deliveryTerms: 'APMC Handover',
      paymentTerms: 'Immediate RTGS / Escrow',
      message: 'Interested in 30 quintals of Shankar-6 for textile mill in Ahmedabad. Please accept our competitive bid.',
    });

    // 5. Seed Price Alerts
    await PriceAlert.create({
      user: farmerRamesh._id,
      cropName: 'Wheat',
      market: 'Gondal Mandi',
      condition: 'above',
      targetPrice: 2450,
      currentPrice: 2450,
      isActive: true,
      isTriggered: true,
      lastTriggeredAt: new Date(),
      notificationType: 'both',
    });

    await PriceAlert.create({
      user: farmerRamesh._id,
      cropName: 'Cotton',
      market: 'Rajkot APMC',
      condition: 'above',
      targetPrice: 7600,
      currentPrice: 7520,
      isActive: true,
      isTriggered: false,
      notificationType: 'both',
    });

    // 6. Seed Government Schemes & MSP Rates
    const schemesData = [
      {
        title: 'Pradhan Mantri Kisan Samman Nidhi (PM-KISAN)',
        category: 'Financial Support',
        ministry: 'Ministry of Agriculture and Farmers Welfare',
        benefitAmount: '₹6,000 / year (Direct DBT in 3 Equal Installments)',
        description: 'Direct income support of ₹6,000 per year given to all landholding farmer families across India directly into their Aadhaar-linked bank accounts.',
        eligibility: ['Small and marginal farmer families with cultivable landholding', 'Valid Aadhaar linked with active bank account', 'State land records (7/12 & 8A in Gujarat) updated'],
        documentsRequired: ['Aadhaar Card', 'Land Ownership Records (Khatauni / 7/12)', 'Bank Passbook copy with IFSC', 'Mobile Number linked to Aadhaar'],
        portalUrl: 'https://pmkisan.gov.in',
      },
      {
        title: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
        category: 'Crop Insurance',
        ministry: 'Ministry of Agriculture and Farmers Welfare',
        benefitAmount: 'Comprehensive cover up to 100% Sum Insured for non-preventable natural risks',
        description: 'Comprehensive financial support to farmers suffering crop loss/damage arising out of unforeseen natural calamities like drought, flood, pests, and unseasonal cyclones.',
        eligibility: ['All farmers including sharecroppers and tenant farmers growing notified crops', 'Farmer must insure crop before official cutoff date each season'],
        documentsRequired: ['Land Possession Certificate', 'Sowing Certificate from Village Talati / Gram Sevak', 'Bank Account details', 'Aadhaar Card'],
        portalUrl: 'https://pmfby.gov.in',
      },
      {
        title: 'PM-KUSUM Solar Agricultural Pumps Scheme',
        category: 'Irrigation & Solar',
        ministry: 'Ministry of New and Renewable Energy (MNRE)',
        benefitAmount: 'Up to 60% Government Subsidy (30% Central + 30% State)',
        description: 'Solarization of grid-connected agriculture pumps and installation of standalone off-grid solar water pumps for reliable daytime irrigation.',
        eligibility: ['Individual farmers with tubewell or open well', 'Panchayats and Farmer Producer Organizations (FPOs)'],
        documentsRequired: ['Electricity connection bill or proof of well', 'Aadhaar Card', 'Land registration document'],
        portalUrl: 'https://pmkusum.mnre.gov.in',
      },
      // MSP Official 2024-2026 Table Records
      {
        title: 'Minimum Support Price (MSP): Wheat 2024-26',
        category: 'MSP',
        benefitAmount: '₹2,425 / quintal (Rabi 2024-25 MSP)',
        description: 'Government announced MSP for Wheat fixed at ₹2,425/quintal, guaranteeing an estimated margin of 105% over cost of production (A2+FL).',
        eligibility: ['All farmers registering with government procurement portal (e-Samridhi / FCI / State Civil Supplies)'],
        documentsRequired: ['Aadhaar Card', 'Farmer Registration ID', 'Bank details'],
        portalUrl: 'https://farmer.gov.in',
        mspCropDetails: {
          cropName: 'Wheat',
          season: 'Rabi',
          msp2023_24: 2275,
          msp2024_25: 2425,
          msp2025_26: 2500,
          marketPriceAvg: 2440,
          unit: '₹/quintal',
        },
      },
      {
        title: 'Minimum Support Price (MSP): Cotton (Medium Staple)',
        category: 'MSP',
        benefitAmount: '₹7,121 / quintal (Kharif 2024-25 MSP)',
        description: 'Government procurement via Cotton Corporation of India (CCI) when market prices drop below official benchmark.',
        eligibility: ['Cotton growers registered on Cotton Corporation portal'],
        documentsRequired: ['Aadhaar', 'Land Record Certificate', 'Ginning Passbook'],
        portalUrl: 'https://cotcorp.org.in',
        mspCropDetails: {
          cropName: 'Cotton',
          season: 'Kharif',
          msp2023_24: 6620,
          msp2024_25: 7121,
          msp2025_26: 7350,
          marketPriceAvg: 7520,
          unit: '₹/quintal',
        },
      },
      {
        title: 'Minimum Support Price (MSP): Groundnut',
        category: 'MSP',
        benefitAmount: '₹6,783 / quintal (Kharif 2024-25 MSP)',
        description: 'NAFED procurement benchmark for fair average quality (FAQ) pods.',
        eligibility: ['Registered oilseed cultivators in Gujarat, AP, Rajasthan, Tamil Nadu'],
        documentsRequired: ['Aadhaar', 'Farmer Samagra ID', '7/12 Land Extract'],
        portalUrl: 'https://nafed-india.com',
        mspCropDetails: {
          cropName: 'Groundnut',
          season: 'Kharif',
          msp2023_24: 6377,
          msp2024_25: 6783,
          msp2025_26: 7000,
          marketPriceAvg: 6490,
          unit: '₹/quintal',
        },
      },
    ];

    await GovernmentScheme.insertMany(schemesData);

    // 7. Seed Crop Advisories
    const advisoriesData = [
      {
        cropName: 'Wheat',
        season: 'Rabi',
        stage: 'Vegetative',
        title: 'Yellow Rust (Stripe Rust) Prevention in Wheat',
        category: 'Disease',
        symptoms: ['Yellow stripes or pustules on the upper leaves', 'Powdery yellow spores rubbing off onto fingers', 'Stunted plant growth if infected early'],
        organicSolution: 'Spray Sour Buttermilk (chaas) mixed with Hing (asafoetida) solution at 5% concentration, or Neem oil 1500 PPM.',
        chemicalSolution: 'Spray Propiconazole 25% EC (Tilt) @ 1 ml per litre of water or Tebuconazole 25.9% EC.',
        recommendedDosage: '200 ml per acre dissolved in 200 litres of water using knapsack sprayer.',
        severity: 'High',
      },
      {
        cropName: 'Cotton',
        season: 'Kharif',
        stage: 'Flowering',
        title: 'Pink Bollworm (PBW) Monitoring and Control',
        category: 'Pest Control',
        symptoms: ['Rosette flowers that fail to open normally', 'Holes in developing bolls plugged with excreta', 'Premature boll dropping and lint staining'],
        organicSolution: 'Install Pheromone Traps @ 5 traps per acre with Phero-sensor lures. Release Trichogramma egg parasitoids @ 60,000/acre.',
        chemicalSolution: 'Spray Chlorantraniliprole 18.5% SC @ 0.3 ml/L or Emamectin Benzoate 5% SG @ 0.5 g/L.',
        recommendedDosage: '60 ml Coragen per acre.',
        severity: 'Critical',
      },
      {
        cropName: 'Tomato',
        season: 'Year-round',
        stage: 'Fruiting',
        title: 'Early Blight & Blossom End Rot Management',
        category: 'Disease',
        symptoms: ['Concentric rings (target board pattern) on lower leaves', 'Sunken black leathery spots at blossom end of fruit', 'Leaf yellowing and defoliation'],
        organicSolution: 'Ensure consistent soil moisture to prevent calcium deficiency. Spray Trichoderma viride @ 5g/L on foliage.',
        chemicalSolution: 'Foliar spray of Mancozeb 75% WP @ 2.5 g/L or Azoxystrobin 23% SC @ 1 ml/L.',
        recommendedDosage: '500g Mancozeb per 200L water per acre.',
        severity: 'Moderate',
      },
      {
        cropName: 'Groundnut',
        season: 'Kharif',
        stage: 'Pod Formation',
        title: 'Tikka Disease (Cercospora Leaf Spot) Control',
        category: 'Disease',
        symptoms: ['Dark brown to black spots surrounded by yellow halos on leaves', 'Premature leaf drop causing bare stems', 'Reduced pod size and oil content'],
        organicSolution: 'Spray Pseudomonas fluorescens @ 10g/litre or Cow urine (10%) + Neem leaf extract.',
        chemicalSolution: 'Spray Carbendazim 12% + Mancozeb 63% WP (Saaf) @ 2g per litre of water.',
        recommendedDosage: '400g Saaf per acre.',
        severity: 'Moderate',
      },
    ];

    await CropAdvisory.insertMany(advisoriesData);

    console.log('✅ KisanSetu database seeding complete: 4 users, 18 mandis, 4 crops, offers, orders, schemes & advisories ready!');
  } catch (error) {
    console.error('Seeding error:', error.message);
  }
};

module.exports = seedData;
